SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Creating [dbo].[Huxley]'
GO
CREATE TABLE [dbo].[Huxley]
(
[Huxley] [nchar] (10) NULL
)
GO

